#!/bin/bash
set -eux

# init - Bootstrap Script for Kubernetes Forge.
#        Generates username and password for the
#        new Kubernetes environment.

# encryption key for the Kubernetes Secrets API
safe gen -l 32 ${CREDENTIALS}/control encryption-key

# X.509 Certificate Authority for all the things (except signing)
safe x509 issue ${CREDENTIALS}/x509/ca \
  --ca -n ca.k8s.deployed.blacksmithproject.io

# X.509 Certificate Authority for signing
safe x509 issue ${CREDENTIALS}/x509/sa \
  --ca -n sa.k8s.deployed.blacksmithproject.io

# Issue an administrator certificate, so that we can
# include it in the credentials we give back to the
# caller via the Blacksmith OSB `bind` op.
safe x509 issue ${CREDENTIALS}/x509/admin \
  --signed-by ${CREDENTIALS}/x509/ca \
  -s /cn=admin/o=system:masters \
  -b 2048 \
  -n admin

exit 0
